### ISSUE TITLE
Create a Python GUI using Custom Tkinter

### ISSUE THREAD

**Issue by damncode12** [damncode12/devitup#1]
Fork and clone the main repo.

Create a folder with your name and add contributor.txt in the sub folder along with the project folder that you developed.
The final tree structure of the folders must be like:
<Folder_with_Name>
-----Project Folder
-----Contributor.txt

Further then open a PR with your new project pushed in this structure discussed above.

_The contributor.txt must be compliant with the Contribution guidelines mentioned in the readme and well as the Contribution.md file on the main repo._

**Comment by akadeepesh** [comment]
Assign this to me, I can do this! It will be good if you want to specify some points, like what i should make on tkinter window

**Comment by 047pegasus** [comment]
Assign it to me.I have expertise in the subject 🔥

**Comment by damncode12** [comment]
Great @047pegasus.Just wow.. what a profile.. Assigning it you right away ✅🚀

**Comment by 047pegasus** [comment]
I have complted the task assigned. Kindly review my PR. ✅

**Comment by damncode12** [comment]
Good work @047pegasus . You did a great Job on this one particularly!! 🚀✅
