### ISSUE TITLE
Advanced CRUD Application using Svelte and PocketBase 

### ISSUE THREAD

**Issue by damncode12** [damncode12/devitup#4]
Fork and clone the main repo.
Create a new branch and add your code in it.
Create a folder with your name and add contributor.txt in the sub folder along with the project folder that you developed.
The final tree structure of the folders must be like:
<Folder_with_Name>
-----Project Folder
-----Contributor.txt

Further then open a PR with your new project pushed in this structure discussed above.

The contributor.txt must be compliant with the Contribution guidelines mentioned in the readme and well as the Contribution.md file on the main repo.

**Comment by 047pegasus** [comment]
Please assign this to me. You can view my expertise in this subject by viewing my profile. 🔥✅

**Comment by damncode12** [comment]
Sure assigned you for the issue 👍🏻

**Comment by damncode12** [comment]
Good work. Closing the issue @047pegasus ✅
