### ISSUE TITLE
Develop an API in Go that uses Postgres or any other backend DB which is CRUD compliant and is useful for managing members in a College Club

### ISSUE THREAD

**Issue by damncode12** [damncode12/devitup#5]
The API must include the following features:
 Have the following endpoints: /join ( for new members to be added to the DB )
/remove ( to remove members of the organization)
/auth (to authenticate user who is performing these operations)
/manage(to change attributes of already existing members in the club)
/eventsAdd (to post upcoming event details to the server)
/eventsInfo (to get information about past events)
/yearMembers( to get details of members per year as per body in the API request)

**Comment by 047pegasus** [comment]
I am experienced in Go and would to develop it for my very own college GDSC community too. I will start working soon on it. ✅

**Comment by damncode12** [comment]
Sure then you are good to go for this one too I guess 😄

**Comment by damncode12** [comment]
Good then, I think it is enough. Well done @047pegasus ✅
